### ISSUE TITLE
ES APM内置支持dubbo

### ISSUE THREAD

**Issue by CoderLan0668** [siyuanWang/springCloudAlibabaAPMDemo#1]
看到你基于ES APM的java agent的public api来实现dubbo的链路追踪，为什么不考虑集成到agent，而是采用filter的方式在项目中实现呢？

**Comment by siyuanWang** [comment]
@CoderLan0668 ,你好，我没有仔细研究过agent，你的想法不错，我可以研究下如何在agent中集成dubbo。我实现的出发点在于链路追踪的**不侵入性和优雅性**。当时第一时间想到的就是dubbo的filter和SpringAOP，然后把这部分实现集成在starter中，通过这种方式既可以自动上报dubbo部分的追踪数据，也可以通过注解的方式，让业务开发工程师能够轻松选择要追踪的方法，满足了我的设计初衷。
